#!/bin/sh

sudo -v

function nocomments {
    sed 's/ *#.*//' "$1" | sed '/^$/d'
}

function oneline {
    $(nocomments "$1") | tr '\n' ' '
}

# install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# run brewfile
nocomments Brewfile | xargs -toL1 brew

# install rvm
curl -sSL https://get.rvm.io | bash -s stable

# update rubygems
sudo gem update --system

# install gems
# gem install $(oneline Gemfile)
gem install $(tr '\n' ' ' < Gemfile)
